// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryWebAPI.Data;

#nullable disable

namespace MusicLibraryWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230919164920_adding_likes_field_to_song_class")]
    partial class adding_likes_field_to_song_class
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryWebAPI.Model.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Forever Young",
                            Artist = "Alphaville",
                            Genre = "New Wave",
                            Likes = 0,
                            ReleaseDate = 1984,
                            Title = "Forever Young"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Kiss Me Kiss Me Kiss Me",
                            Artist = "The Cure",
                            Genre = "New Wave",
                            Likes = 0,
                            ReleaseDate = 1987,
                            Title = "Just Like Heaven"
                        },
                        new
                        {
                            Id = 3,
                            Album = "When In Rome",
                            Artist = "When In Rome",
                            Genre = "New Wave",
                            Likes = 0,
                            ReleaseDate = 1988,
                            Title = "The Promise"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Songs From The Big Chair",
                            Artist = "Tears For Fears",
                            Genre = "New Wave",
                            Likes = 0,
                            ReleaseDate = 1985,
                            Title = "Everybody Wants To Rule The World"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Japanese Whispers",
                            Artist = "The Cure",
                            Genre = "New Wave",
                            Likes = 0,
                            ReleaseDate = 1983,
                            Title = "The Lovecats"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
